export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';

export const GET_VENUE = 'GET_VENUE';
export const VENUE_LOADING = 'VENUE_LOADING';
export const REMOVE_VENUE_LOADING = 'REMOVE_VENUE_LOADING';
export const VENUE_NOT_FOUND = 'VENUE_NOT_FOUND';
export const CLEAR_CURRENT_VENUE = 'CLEAR_CURRENT_VENUE';
export const GET_VENUES = 'GET_VENUES';
export const SAVE_VENUE = 'SAVE_VENUE';

export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const INGREDIENTS_LOADING = 'INGREDIENTS_LOADING';
export const INGREDIENTS_LOADING_FALSE = 'INGREDIENTS_LOADING_FALSE';
export const SAVE_PROFILE_INGREDIENT = 'SAVE_PROFILE_INGREDIENT';
export const SET_SELECTED_INGREDIENT = 'SET_SELECTED_INGREDIENT';
export const REMOVE_SELECTED_INGREDIENT =
  'REMOVE_SELECTED_INGREDIENT';
export const SET_SELECTED_INGREDIENT_SUPPLIER =
  'SET_SELECTED_INGREDIENT_SUPPLIER';

export const GET_SUPPLIERS = 'GET_SUPPLIERS';
export const SUPPLIERS_LOADING = 'SUPPLIERS_LOADING';

export const GET_RECIPE = 'GET_RECIPE';
export const RECIPE_LOADING = 'RECIPE_LOADING';
export const RECIPE_NOT_FOUND = 'RECIPE_NOT_FOUND';
export const CLEAR_CURRENT_RECIPE = 'CLEAR_CURRENT_RECIPE';
export const GET_RECIPES = 'GET_RECIPES';
export const SAVE_RECIPE = 'SAVE_RECIPE';
